version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_dev
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdev
    volumes:
      - ./src:/var/www/html/wp-content
    restart: always

  db:
    image: mariadb:10.6
    container_name: wordpress_dev_db
    environment:
      MYSQL_DATABASE: wpdev
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - devdb:/var/lib/mysql
    restart: always

volumes:
  devdb:
